wordpress:
  build: dev/wordpress
  ports:
    - 80:80
  links:
    - db:mysql
  volumes:
    - ./wordpress:/var/www/html
  environment:
    WP_VERSION: 4.5.3

db:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: password
